remote_theme: aterenin/minima-reboot
title: App Privacy
author: IncoderApp
description: ""

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
- about.md
- posts.md

footer_icons:
  - username: Privacy
    url: https://github.com/IncoderApp/Privacy
    icon: icon-github.svg

markdown: kramdown

paginate: 5